import {
  Home,
  Search,
  Compass,
  BookOpen,
  LogIn,
  Heart,
  User,
  ClipboardCheck,
  Building2,
  LayoutDashboard,
} from "lucide-react";
import type { NavItemConfig } from "@/types/navigation";

export const NAV_ITEMS_CONFIG: NavItemConfig[] = [
  // ANCHORED ITEMS — Always at specific positions
  {
    id: "home",
    icon: Home,
    label: "Home",
    path: "/",
    requiredFeature: null,
    requiresAuth: false,
    badgeSource: null,
    priority: 100,
    anchor: 0,
  },
  {
    id: "explore",
    icon: Search,
    label: "Explore",
    path: "/listings",
    requiredFeature: null,
    requiresAuth: false,
    badgeSource: null,
    priority: 95,
    anchor: 1,
  },
  {
    id: "login",
    icon: LogIn,
    label: "Login",
    path: "/auth",
    requiredFeature: null,
    requiresAuth: false,
    badgeSource: null,
    priority: 60,
    anchor: 4,
  },

  // FLOATING ITEMS — Ranked by priority
  {
    id: "hunter",
    icon: Compass,
    label: "Hunter",
    path: "/hunter",
    requiredFeature: null,
    requiresAuth: false,
    badgeSource: null,
    priority: 90,
  },
  {
    id: "learn",
    icon: BookOpen,
    label: "Learn",
    path: "/learn",
    requiredFeature: null,
    requiresAuth: false,
    badgeSource: null,
    priority: 80,
  },
  {
    id: "saved",
    icon: Heart,
    label: "Saved",
    path: "/saved",
    requiredFeature: null,
    requiresAuth: true,
    badgeSource: null,
    priority: 70,
  },
  {
    id: "inspections",
    icon: ClipboardCheck,
    label: "Inspections",
    path: "/inspections",
    requiredFeature: "inspections.view",
    requiresAuth: true,
    badgeSource: "notifications",
    priority: 75,
  },
  {
    id: "properties",
    icon: Building2,
    label: "Properties",
    path: "/properties",
    requiredFeature: "properties.manage",
    requiresAuth: true,
    badgeSource: null,
    priority: 75,
  },
  {
    id: "overview",
    icon: LayoutDashboard,
    label: "Overview",
    path: "/admin",
    requiredFeature: "admin.overview",
    requiresAuth: true,
    badgeSource: null,
    priority: 85,
  },
  {
    id: "you",
    icon: User,
    label: "You",
    path: "/profile",
    requiredFeature: null,
    requiresAuth: true,
    badgeSource: "notifications",
    priority: 65,
  },
];
